name: Publish

on: 
  workflow_dispatch: 
  push:
    branches: 
      - main

env:
  AZURE_WEBAPP_NAME: routewiseapp-api-dkf9echbgpb3a7b8
  AZURE_WEBAPP_PACKAGE_PATH: "./RouteWiseApp/RouteWiseAPP.API/publish"

jobs:
  publish: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./RouteWiseApp/RouteWiseAPP.API/RouteWiseApp.sln

      - name: Build
        run: dotnet build ./RouteWiseApp/RouteWiseAPP.API/RouteWiseApp.sln --configuration Release --no-restore 

      - name: Publish
        run: dotnet publish ./RouteWiseApp/RouteWiseAPP.API/RouteWiseApp.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      
